spring:
  application:
    name: xphr-demo
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/staff
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp