create table xphr.employee
(
    id   bigint generated by default as identity
        primary key,
    name varchar(60)
);

create table xphr.project
(
    id   bigint generated by default as identity
        primary key,
    name varchar(200)
);

create table xphr.time_record
(
    id          bigint generated by default as identity
        primary key,
    employee_id integer   not null,
    project_id  integer   not null,
    time_from   timestamp not null,
    time_to     timestamp not null
);

